---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: weebcast-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weebcast-operator-role
subjects:
  - kind: ServiceAccount
    name: weebcast-operator
    namespace: weebcast-system

