---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weebcast-operator
  namespace: weebcast-system
  labels:
    app.kubernetes.io/name: weebcast-operator
    app.kubernetes.io/component: controller

