apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weebcast-system

resources:
  - crd/weebcast.com_animemonitors.yaml
  - rbac/service_account.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml
  - manager/deployment.yaml

